columnSuffix: null
handle: newsDescription
instructions: 'Add a news description to be displayed. Length will be limited to 250 characters when displayed on the website.'
name: 'News Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Rowmark LLC introduces The Naturals product line, an authentic, nature-inspired, textured engravable sheet product. The Naturals not only look like they came right from the outdoors, but they feel like it too. And just like their real-life counterparts,…'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
